apiVersion: v1
kind: Service
metadata:
  name: tallerprueba
  labels:
    app: tallerprueba
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: tallerprueba
  type: LoadBalancer  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tallerprueba
  labels:
    app: tallerprueba
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tallerprueba
    spec:
      containers:
      - image: contenedorestaller.azurecr.io/proyecto
        name: tallerprueba
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: secretpruebataller
---      
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tallerprueba
spec:
  scaleTargetRef:
    kind: Deployment
    name: tallerprueba
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70